Handle -state-out and path to terraform dir.

diff --git a/dev/test/bin/terragrunt_wrapper_test b/dev/test/bin/terragrunt_wrapper_test
--- a/dev/test/bin/terragrunt_wrapper_test
+++ b/dev/test/bin/terragrunt_wrapper_test
@@ -19,18 +19,20 @@ skip_next_apply_file="terragrunt_wrapper.skip_next_apply"
 out=$($base_cmd whatever -state=$tmp_state_dir/state -destroy=true)
 echo $out | grep -q "Would have created: $tmp_state_dir/$skip_next_apply_file" && success || fail "$out"
 
-echo -n "plan + -state + -destroy=true -> destroy-all..."
-out=$($base_cmd plan -state=/path/to/some/state -destroy=true)
+echo -n "plan + -state + -destroy=true + path -> destroy-all..."
+out=$($base_cmd plan -state=/path/to/some/state -destroy=true /path/to/tf/dir)
 echo $out | grep -q "destroy-all" && success || fail "$out"
 echo -n "..."
 ! echo $out | grep -q -- "-destroy=true" && success || fail "$out"
+echo -n "..."
+! echo $out | grep -q "/path/to/tf/dir" && success || fail "$out"
 
 echo -n "apply + skip_next_apply -> skip apply..."
 tmp_state_dir="terragrunt_wrapper_test.tmp"
 skip_next_apply_file="terragrunt_wrapper.skip_next_apply"
 mkdir "$tmp_state_dir" || fail "Couldn't mkdir $tmp_state_dir. Delete it and try again."
 touch "$tmp_state_dir/$skip_next_apply_file"
-out=$($base_cmd apply -state=$tmp_state_dir/state)
+out=$($base_cmd apply -state-out=$tmp_state_dir/state)
 rm -f "$tmp_state_dir/$skip_next_apply_file"
 rmdir "$tmp_state_dir"
 echo $out | grep -q "Skipping this apply" && success || fail "$out"
