Restrict heroic measures to output-all.

diff --git a/dev/test/bin/terragrunt_wrapper b/dev/test/bin/terragrunt_wrapper
--- a/dev/test/bin/terragrunt_wrapper
+++ b/dev/test/bin/terragrunt_wrapper
@@ -47,12 +47,19 @@ massaged_args=$(echo "$*" \
     | sed -e 's#[^[:blank:]]*terraform.tfplan##g' \
     | sed -e 's#-state=[^[:blank:]]*##g' \
 )
-cmd="terragrunt $massaged_args --terragrunt-non-interactive --terragrunt-ignore-dependency-errors"
+cmd="terragrunt $massaged_args --terragrunt-non-interactive"
+if echo "$cmd" | grep -Eq "\boutput-all\b" ; then
+    cmd="$cmd --terragrunt-ignore-dependency-errors"
+fi
 if echo "$cmd" | grep -Eq "\W-json=true\b" ; then
     cmd="$cmd | jq -s 'add'"
+fi
+# Repeat this check because this trap for non-zero exit needs to be the very last thing.
+if echo "$cmd" | grep -Eq "\boutput-all\b" ; then
+    cmd="$cmd || echo \"Command ($cmd) exited non-zero. I'm returning zero anyway to cover failures in output-all.\""
 fi
 if [ -n "$DRY_RUN" ] ; then
     echo "Dry run! Would have run: $cmd"
 else
-    eval $cmd || echo "Command ($cmd) exited non-zero. I'm returning zero anyway to cover failures in output-all."
+    eval $cmd
 fi
diff --git a/dev/test/bin/terragrunt_wrapper_test b/dev/test/bin/terragrunt_wrapper_test
--- a/dev/test/bin/terragrunt_wrapper_test
+++ b/dev/test/bin/terragrunt_wrapper_test
@@ -45,6 +45,13 @@ echo -n "-state -> deleted..."
 out=$($base_cmd whatever -state=/path/to/some/state)
 ! echo $out | grep -q "/some/state" && success || fail "$out"
 
+echo -n "output -> ignore-dependency-errors..."
+out=$($base_cmd output)
+echo $out | grep -q -- "--terragrunt-ignore-dependency-errors" && success || fail "$out"
 echo -n "-json -> jq..."
 out=$($base_cmd whatever -json=true)
 echo $out | grep -q "jq" && success || fail "$out"
+
+echo -n "output -> || exit 0..."
+out=$($base_cmd output)
+echo $out | grep -q -- "|| echo" && success || fail "$out"
