Get rid of -destroy=true as terragrunt hates it.

diff --git a/dev/test/bin/terragrunt_wrapper_test b/dev/test/bin/terragrunt_wrapper_test
--- a/dev/test/bin/terragrunt_wrapper_test
+++ b/dev/test/bin/terragrunt_wrapper_test
@@ -22,6 +22,8 @@ echo $out | grep -q "Would have created: $tmp_state_dir/$skip_next_apply_file" &
 echo -n "plan + -state + -destroy=true -> destroy-all..."
 out=$($base_cmd plan -state=/path/to/some/state -destroy=true)
 echo $out | grep -q "destroy-all" && success || fail "$out"
+echo -n "..."
+! echo $out | grep -q -- "-destroy=true" && success || fail "$out"
 
 echo -n "apply + skip_next_apply -> skip apply..."
 tmp_state_dir="terragrunt_wrapper_test.tmp"
