Derp, I can just use *.

diff --git a/dev/test/bin/terragrunt_wrapper_test b/dev/test/bin/terragrunt_wrapper_test
--- a/dev/test/bin/terragrunt_wrapper_test
+++ b/dev/test/bin/terragrunt_wrapper_test
@@ -39,7 +39,7 @@ echo $out | grep -q "destroy-all" && success || fail "$out"
 
 echo -n "terraform.tfplan -> deleted..."
 out=$($base_cmd whatever -out=/path/to/terraform.tfplan)
-! echo $out | grep -q "terraform.tfplan" && success || fail "$out"
+! echo $out | grep -q -- "-out=" && success || fail "$out"
 
 echo -n "-state -> deleted..."
 out=$($base_cmd whatever -state=/path/to/some/state)
